# Generated by Django 6.0.3 on 2026-08-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_set_user_permissions', 'User can add permissions'), ('can_see_user_permissions', 'User can set permissions list')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
